java:
  stage: test
  image: maven:latest
  script:
    - mvn -B package --file pom.xml
    - mvn -B test --file pom.xml
    - bundle install
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
